<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>$schema</key>
    <string>https://raw.githubusercontent.com/martinring/tmlanguage/master/tmlanguage.json</string>
    <key>name</key>
    <string>Plain-English</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#keywords</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#strings</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>keywords</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>keyword.control.plain</string>
            <key>match</key>
            <string>\b(a|above|an|and|another|are|at|bigger than|blank|bottom|by|Call|call|called|cancel|divided by|equal to|for|from|given|has|in|inch|inches|Intel|into|is|left|less than|like|Loop|loop|minus|multiplied by|nil|no|of|other|pixel|pixels|plus|Repeat|repeat|right|'s|Say|say|set|some|the|then|To|to|top|using|was|with|with|yes)\b</string>
          </dict>
        </array>
      </dict>
      <key>strings</key>
      <dict>
        <key>name</key>
        <string>string.quoted.double.plain</string>
        <key>begin</key>
        <string>"</string>
        <key>end</key>
        <string>"</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>constant.character.escape.plain</string>
            <key>match</key>
            <string>\\.</string>
          </dict>
        </array>
      </dict>
    </dict>
    <key>scopeName</key>
    <string>source.plain</string>
  </dict>
</plist>