# Este fluxo de trabalho fará a triagem de solicitações pull e aplicará um rótulo com base nas
# pastas que forem modificados na solicitação pull.
#
# Para usar este fluxo de trabalho, você precisará configurar um arquivo .github/labeler.yml
# Para mais informações, veja:
# https://github.com/actions/labeler

name: Labeler
on: [pull_request]

jobs:
  label:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/labeler@v2
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
